graph LR
    subgraph CN["client-net 172.21.0.0/24"]
        CL[test-client<br/>172.21.0.100] -- default gw --> F1
        F1[FRR1 TOR-Client<br/>AS 65100<br/>172.21.0.10]
    end
    F1 -->|transit-net eBGP| F2
    subgraph TN["transit-net 172.23.0.0/24"]
        F2[FRR2 TOR-Cluster<br/>AS 65000<br/>172.23.0.2<br/>default gateway for nodes]
    end
    subgraph BN["bgp-net 172.19.0.0/16"]
        F2
        CP[K8s CP<br/>172.19.0.3<br/>no BGP]
        WK[K8s Worker 1<br/>172.19.0.4<br/>AS 65001<br/>pod 10.244.1.5]
        WK2[K8s Worker 2<br/>172.19.0.5<br/>AS 65001<br/>pod 10.244.2.7]
        LB[LB VIP 172.19.0.200/32]
    end
    F2 -->|eBGP ECMP| WK
    F2 -->|eBGP ECMP| WK2
    WK -.->|advertise 172.19.0.200/32| F2
    WK2 -.->|advertise 172.19.0.200/32| F2
    WK -->|default gateway| F2
    WK2 -->|default gateway| F2
