frr defaults datacenter
hostname spine-border
!
interface eth1
  ip address 10.99.0.9/31
!
interface eth2
  ip address 10.99.0.14/31
!
router bgp 65201
  bgp router-id 10.99.0.9
  no bgp ebgp-requires-policy
  neighbor 10.99.0.8 remote-as 65200
  neighbor 10.99.0.8 timers connect 5
  neighbor 10.99.0.8 bfd
  neighbor 10.99.0.15 remote-as 65001
  neighbor 10.99.0.15 timers connect 5
  neighbor 10.99.0.15 bfd
  address-family ipv4 unicast
    neighbor 10.99.0.8 activate
    neighbor 10.99.0.15 activate
    neighbor 10.99.0.15 default-originate
    redistribute connected
  exit-address-family
!
bfd
  peer 10.99.0.8
    detect-multiplier 3
    receive-interval 50
    transmit-interval 50
  peer 10.99.0.15
    detect-multiplier 3
    receive-interval 50
    transmit-interval 50
!
