frr defaults datacenter
hostname spine-fabric

interface eth1
  ip address 10.99.0.5/31
!
interface eth2
  ip address 10.99.0.7/31
!
interface eth3
  ip address 10.99.0.8/31
!
interface eth4
  ip address 10.99.0.11/31
!
interface eth5
  ip address 10.99.0.13/31
!
router bgp 65200
  bgp router-id 10.99.0.5
  no bgp ebgp-requires-policy
  neighbor 10.99.0.4 remote-as 65101
  neighbor 10.99.0.4 bfd
  neighbor 10.99.0.6 remote-as 65102
  neighbor 10.99.0.6 bfd
  neighbor 10.99.0.9 remote-as 65201
  neighbor 10.99.0.9 bfd
  neighbor 10.99.0.10 remote-as 65101
  neighbor 10.99.0.10 bfd
  neighbor 10.99.0.12 remote-as 65102
  neighbor 10.99.0.12 bfd
  address-family ipv4 unicast
    neighbor 10.99.0.4 activate
    neighbor 10.99.0.6 activate
    neighbor 10.99.0.9 activate
    neighbor 10.99.0.10 activate
    neighbor 10.99.0.12 activate
    neighbor 10.99.0.4 default-originate
    neighbor 10.99.0.6 default-originate
    neighbor 10.99.0.10 default-originate
    neighbor 10.99.0.12 default-originate
    redistribute connected
  exit-address-family
!
bfd
  peer 10.99.0.4
    detect-multiplier 3
    receive-interval 50
    transmit-interval 50
  peer 10.99.0.6
    detect-multiplier 3
    receive-interval 50
    transmit-interval 50
  peer 10.99.0.9
    detect-multiplier 3
    receive-interval 50
    transmit-interval 50
  peer 10.99.0.10
    detect-multiplier 3
    receive-interval 50
    transmit-interval 50
  peer 10.99.0.12
    detect-multiplier 3
    receive-interval 50
    transmit-interval 50
!
