frr version 8.4_git
frr defaults traditional
hostname tor-mock-2
log file /tmp/frr.log
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65000
 bgp router-id 172.18.0.50
 bgp bestpath as-path multipath-relax
 neighbor K8S-WORKERS peer-group
 neighbor K8S-WORKERS remote-as 65100
 neighbor K8S-WORKERS bfd
 bgp listen limit 10
 bgp listen range 172.18.0.0/16 peer-group K8S-WORKERS
 !
 address-family ipv4 unicast
  neighbor K8S-WORKERS activate
  neighbor K8S-WORKERS route-map IMPORT in
  neighbor K8S-WORKERS route-map EXPORT out
 exit-address-family
exit
!
ip prefix-list IMPORT seq 5 permit 192.168.0.0/16 le 32
ip prefix-list IMPORT seq 10 permit 10.0.0.0/8 le 32
ip prefix-list IMPORT seq 15 permit 0.0.0.0/0 le 32
ip prefix-list EXPORT seq 5 permit 10.0.0.0/8
ip prefix-list EXPORT seq 10 permit 172.16.0.0/12
!
route-map IMPORT permit 10
 match ip address prefix-list IMPORT
exit
!
route-map EXPORT permit 10
 match ip address prefix-list EXPORT
exit
!
bfd
 detect-multiplier 3
 receive-interval 300
 transmit-interval 300
exit
!
