frr defaults datacenter
hostname k8s-control-plane
!
interface lo
!
interface eth1
  ip address 10.99.0.15/31
!
interface eth0
  shutdown
!
interface dummy0
  ip address 10.99.255.10/32
!
ip prefix-list PL-ANY seq 5 permit 0.0.0.0/0 le 32
!
route-map TO-CILIUM deny 10
  description Advertise nothing to Cilium (receive-only peer)
  match ip address prefix-list PL-ANY
!
route-map FROM-CILIUM permit 10
  description Rewrite Cilium loopback (127.0.0.1) next-hop to a reachable local IP so routes are valid/re-advertised
  set ip next-hop 10.99.255.10
!
router bgp 65001
  bgp router-id 10.99.0.15
  no bgp ebgp-requires-policy
  bgp allow-martian-nexthop
  maximum-paths 2
  bgp bestpath as-path multipath-relax
  neighbor 10.99.0.14 remote-as 65201
  neighbor 10.99.0.14 timers connect 5
  neighbor 10.99.0.14 bfd
  neighbor 10.99.0.14 next-hop-self
  neighbor 127.0.0.1 remote-as 64512
  neighbor 127.0.0.1 description Cilium
  neighbor 127.0.0.1 passive
  neighbor 127.0.0.1 update-source lo
  address-family ipv4 unicast
    neighbor 10.99.0.14 activate
    neighbor 127.0.0.1 activate
    neighbor 127.0.0.1 route-map FROM-CILIUM in
    neighbor 127.0.0.1 route-map TO-CILIUM out
    network 10.99.255.10/32
    table-map KERNEL-FIB
  exit-address-family
!
ip prefix-list DEFAULT-ONLY seq 5 permit 0.0.0.0/0
!
route-map KERNEL-FIB permit 10
  match ip address prefix-list DEFAULT-ONLY
!
bfd
  peer 10.99.0.14
    detect-multiplier 3
    receive-interval 50
    transmit-interval 50
!
