---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bird3-config
  namespace: kube-system
data:
  bird.conf: |
    log stderr all;

    # __NODE_IP__ is replaced by init container via Downward API status.hostIP
    router id __NODE_IP__;

    protocol kernel {
        persist;
        scan time 60;
        ipv4 {
            import none;
            export none;
        };
    }

    protocol device {
        scan time 10;
    }

    protocol direct {
        ipv4;
    }

    protocol bgp cilium_local {
        local 127.0.0.1 as 65100;
        neighbor 127.0.0.1 as 64512;

        passive on;
        multihop 2;

        ipv4 {
            import all;
            export none;
        };
    }

    # The following placeholder is replaced by init container with one BFD + BGP block
    # per detected default gateway (TOR IP).
    __TOR_PEERS__
