apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
  podSubnet: "10.99.42.0/24"
  serviceSubnet: "10.96.0.0/12"
nodes:
  - role: control-plane
    extraMounts: []
    kubeadmConfigPatches:
      - |
        apiVersion: kubeadm.k8s.io/v1beta3
        kind: ClusterConfiguration
        apiServer:
          certSANs:
            - "10.99.0.15"
            - "127.0.0.1"
  - role: worker
  - role: worker
