graph LR
    subgraph R1["Rack 1"]
        subgraph CN["client-net 172.21.0.0/24"]
            CL["test-client
                Alpine
                172.21.0.100
                curl LB VIP"]
            F1["FRR1 TOR
                bgpd+zebra ip_forward
                AS 65100
                172.21.0.10 / 172.23.0.1"]
        end
    end

    F1 ==>|transit-net 172.23.0.0/24 eBGP| F2

    subgraph R2["Rack 2"]
        subgraph BN["bgp-net 172.19.0.0/16"]
            F2["FRR2 Border
                bgpd+zebra ip_forward
                AS 65000
                172.19.0.10 / 172.23.0.2
                next-hop-self"]
            CP["K8s Control Plane
                172.19.0.3
                Cilium BGP CP
                AS 65001"]
            WK["K8s Worker 1
                172.19.0.4
                Cilium BGP CP
                AS 65001"]
            WK2["K8s Worker 2
                172.19.0.5
                Cilium BGP CP
                AS 65001"]
        end
    end

    F2 ==>|eBGP ECMP  LB VIP 172.19.0.200/32| CP
    F2 ==>|eBGP ECMP  LB VIP 172.19.0.200/32| WK
    F2 ==>|eBGP ECMP  LB VIP 172.19.0.200/32| WK2

    CL -.->|default gateway| F1
