frr defaults datacenter
hostname rack1-tor-a

interface eth1
  ip address 10.99.0.1/31
!
interface eth3
  ip address 10.99.0.4/31
!
interface eth0
  shutdown
!
router bgp 65101
  bgp router-id 10.99.0.1
  no bgp ebgp-requires-policy
  neighbor 10.99.0.0 remote-as 65001
  neighbor 10.99.0.0 timers connect 5
  neighbor 10.99.0.0 bfd
  neighbor 10.99.0.5 remote-as 65200
  neighbor 10.99.0.5 timers connect 5
  neighbor 10.99.0.5 bfd
  address-family ipv4 unicast
    neighbor 10.99.0.0 activate
    neighbor 10.99.0.5 activate
    redistribute connected
  exit-address-family
!
bfd
  peer 10.99.0.0
    detect-multiplier 3
    receive-interval 50
    transmit-interval 50
  peer 10.99.0.5
    detect-multiplier 3
    receive-interval 50
    transmit-interval 50
!
